sudo: false
language: node_js
node_js: '8'
cache:
  directories:
  - node_modules
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      # needed by nodegit (repo-cooker)
      - libstdc++-4.9-dev
git:
  depth: 9999
notifications:
  email: false
script:
- |
  if [[ $SKIP_TESTS != 'true' ]]; then
    npm run lint;
    npm test;
  fi
after_success:
- |
  if [[ $TRAVIS_SECURE_ENV_VARS == 'true' ]]; then
    git remote set-url origin https://lucidogen-bot:${GH_TOKEN}@github.com/lucidogen/ts-project;
    git config --global user.email "bot@lucidogen.io";
    git config --global user.name "Lucidogen Bot";
  fi
  if [[ $TRAVIS_BRANCH == 'master' || $TRAVIS_PULL_REQUEST == 'true' ]]; then
    # repo-cooker coverage:upload;
  fi
  if [[ $TRAVIS_BRANCH == 'master' || $TRAVIS_BRANCH == 'next' ]] && [[ $TRAVIS_PULL_REQUEST == 'false' ]]; then
    printf "//registry.npmjs.org/:_authToken=$NPM_TOKEN\n" > ~/.npmrc;
    npm install --no-save nodegit@0.20.3;
    npm run release;
  fi
branches:
  except:
  - "/^v\\d+\\.\\d+\\.\\d+$/"
